export const fonts = {
  displayLarge: {
    fontFamily: 'DMMono-Medium',
    fontSize: 57,
    lineHeight: 58,
    letterSpacing: 0,
  },
  displayMedium: {
    fontFamily: 'DMMono-MediumItalic',
    fontSize: 40,
    lineHeight: 50,
    letterSpacing: 0,
  },
  displaySmall: {
    fontFamily: 'DMMono-Medium',
    fontSize: 24,
    lineHeight: 34,
    letterSpacing: 0,
  },
  headlineLarge: {
    fontFamily: 'DMMono-Medium',
    fontSize: 32,
    lineHeight: 40,
    letterSpacing: 0,
  },
  headlineMedium: {
    fontFamily: 'DMMono-Medium',
    fontSize: 28,
    lineHeight: 36,
    letterSpacing: 0,
  },
  headlineSmall: {
    fontFamily: 'DMMono-Medium',
    fontSize: 24,
    lineHeight: 32,
    letterSpacing: 0,
  },
  titleItalicLarge: {
    fontFamily: 'DMMono-MediumItalic',
    fontSize: 22,
    lineHeight: 28,
    letterSpacing: 0,
  },
  titleLarge: {
    fontFamily: 'DMMono-Medium',
    fontSize: 22,
    lineHeight: 28,
    letterSpacing: 0,
  },
  titleMedium: {
    fontFamily: 'DMMono-Medium',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0,
  },
  titleSmall: {
    fontFamily: 'DMMono-Medium',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
  },
  labelLarge: {
    fontFamily: 'DMMono-Medium',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
  },
  labelMedium: {
    fontFamily: 'DMMono-Medium',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0,
  },
  labelSmall: {
    fontFamily: 'DMMono-Medium',
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0,
  },
  bodyLarge: {
    fontFamily: 'DMMono-Medium',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0,
  },
  bodyLargeItalic: {
    fontFamily: 'DMMono-MediumItalic',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0,
  },
  bodyMedium: {
    fontFamily: 'DMMono-Medium',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
  },
  bodyMediumItalic: {
    fontFamily: 'DMMono-MediumItalic',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
  },
  bodySmall: {
    fontFamily: 'DMMono-Medium',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0,
  },
  bodySmallItalic: {
    fontFamily: 'DMMono-MediumItalic',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0,
  },
};
